version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: vnedreid
      POSTGRES_PASSWORD: password
      POSTGRES_DB: avitoDb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://app:password@db:5432/appdb
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db_data:
